# -*- coding: utf-8 -*-
"""PairDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FVtjo2SnYfNGraQaKJxzFVgxRaNkb5P
"""

import os
import random
import torch
import torchaudio
from torch.utils.data import Dataset

class PairDataset(Dataset):
    def __init__(self, base_dir):
        super().__init__()
        self.base_dir = base_dir

        self.all_files = []      # [(spk_id, lang_id, filepath), ...]
        self.lang_to_files = {}  # lang_id -> [(spk_id, lang_id, filepath), ...]
        self.spk_to_files = {}   # spk_id -> [(spk_id, lang_id, filepath), ...]

        self._index_dataset()

    def _index_dataset(self):
        """Construye los diccionarios simplificados recorriendo el directorio."""
        for spk in sorted(os.listdir(self.base_dir)):
            spk_path = os.path.join(self.base_dir, spk)
            if not os.path.isdir(spk_path): continue

            if spk not in self.spk_to_files:
                self.spk_to_files[spk] = []

            for lang in sorted(os.listdir(spk_path)):
                lang_path = os.path.join(spk_path, lang)
                if not os.path.isdir(lang_path): continue

                if lang not in self.lang_to_files:
                    self.lang_to_files[lang] = []

                for wav_file in os.listdir(lang_path):
                    if not wav_file.endswith('.wav'): continue

                    full_path = os.path.join(lang_path, wav_file)
                    file_info = (spk, lang, full_path)

                    self.all_files.append(file_info)
                    self.lang_to_files[lang].append(file_info)
                    self.spk_to_files[spk].append(file_info)

        self.all_langs = list(self.lang_to_files.keys())

    def __len__(self):
        return len(self.all_files)

    def _same_lang_sampling(self, anchor_spk, anchor_lang, anchor_path):
        """Sample a random file from the same language."""
        choices = self.lang_to_files[anchor_lang]
        pair_spk, pair_lang, pair_path = random.choice(choices)
        # Avoid, if posible, the anchor
        if len(choices) > 1:
            while pair_path == anchor_path:
                pair_spk, pair_lang, pair_path = random.choice(choices)
        return pair_spk, pair_lang, pair_path

    def _diff_lang_sampling(self, anchor_spk, anchor_lang, anchor_path):
        """Sample a random file from a different language."""
        pair_lang = random.choice(self.all_langs)
        while pair_lang == anchor_lang:
            pair_lang = random.choice(self.all_langs)
        choices = self.lang_to_files[pair_lang]
        pair_spk, pair_lang, pair_path = random.choice(choices)
        return pair_spk, pair_lang, pair_path

    def _same_spk_sampling(self, anchor_spk, anchor_lang, anchor_path):
        """Sample a random file from the same speaker."""
        choices = self.spk_to_files[anchor_spk]
        pair_spk, pair_lang, pair_path = random.choice(choices)
        # Avoid, if posible, the anchor
        if len(choices) > 1:
            while pair_path == anchor_path:
                pair_spk, pair_lang, pair_path = random.choice(choices)
        return pair_spk, pair_lang, pair_path


    def __getitem__(self, idx):
        # 1. Get the anchor file
        anchor_spk, anchor_lang, anchor_path = self.all_files[idx]

        # 2. Decide sampling type and sample
        sampling_func = random.choice((self._same_lang_sampling, self._diff_lang_sampling, self._same_spk_sampling))
        pair_spk, pair_lang, pair_path = sampling_func(anchor_spk, anchor_lang, anchor_path)

        # 3. Set the lang label (1.0: same language, 0.0: diff language)
        label = 1.0 if anchor_lang == pair_lang else 0.0

        # 4. Cargar tensores
        anchor_audio, _ = torchaudio.load(anchor_path)
        pair_audio, _ = torchaudio.load(pair_path)

        return anchor_audio, pair_audio, torch.tensor(label, dtype=torch.float32)

if __name__ == "__main__":

    BASE_DIR = "/home/data/Odyssey2026/TidyLang_Challenge/"
    TRAIN_DIR = BASE_DIR + "TidyVoiceX_ASV/TidyVoiceX_Train"

    # 1. Instanciar el dataset (asegúrate de que "data" exista en tu directorio)
    dataset = PairDataset(TRAIN_DIR)


    import matplotlib.pyplot as plt

    # 2. Extraer un ejemplo aleatorio (o el primero con dataset[0])
    anchor_audio, pair_audio, label = dataset[0]

    # 3. Preparar los tensores para visualización
    # Usamos .squeeze() para pasar de (1, N) a (N,) y .numpy() para que matplotlib lo entienda.
    anchor_np = anchor_audio.squeeze().numpy()
    pair_np = pair_audio.squeeze().numpy()

    # 4. Configurar y mostrar el gráfico
    plt.figure(figsize=(14, 4))

    # Subplot izquierdo: Señal Anchor
    plt.subplot(1, 2, 1)
    plt.plot(anchor_np, color='blue', alpha=0.7)
    plt.title("Señal Anchor")
    plt.xlabel("Muestras (Samples)")
    plt.ylabel("Amplitud")
    plt.grid(True, linestyle='--', alpha=0.5)

    # Subplot derecho: Señal Pair
    plt.subplot(1, 2, 2)
    # Usamos el valor de la etiqueta para el título
    tipo_par = "Mismo Idioma" if label.item() == 1.0 else "Distinto Idioma"
    plt.plot(pair_np, color='orange', alpha=0.7)
    plt.title(f"Señal Pair - {tipo_par} (Label: {label.item()})")
    plt.xlabel("Muestras (Samples)")
    plt.ylabel("Amplitud")
    plt.grid(True, linestyle='--', alpha=0.5)

    plt.tight_layout()
    plt.show()